name: Npm publish

on:
  push:
    branches:
      - 'main'

  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: 'Automated Version Bump'
        uses: 'phips28/gh-action-bump-version@master'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PACKAGEJSON_DIR: 'projects/ui'
        with:
          minor-wording: 'feat:'
          major-wording: 'feat!:,chore!:'
          patch-wording: 'patch,fixes'     # Providing patch-wording will override commits
          # defaulting to a patch bump.
          rc-wording: 'RELEASE,alpha'
      - name: Bootstrap
        run: |
          npm install
      - name: Build
        run: |
          npm run build
      - name: Release npm
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          echo "//registry.npmjs.org/:_authToken=\${NPM_TOKEN}" > ./dist/ui/.npmrc
          npm run publish-on-npm
